//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public int Id { get; set; }
        public int IdCubiculo { get; set; }
        public System.TimeSpan HoraInicial { get; set; }
        public System.TimeSpan HoraFinal { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estatus { get; set; }
    
        public virtual Cubiculo Cubiculo { get; set; }
    }
}
