//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public string ID_Estudiante { get; set; }
        public int ID_Entidad { get; set; }
        public int ID_Carrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Entidad Entidad { get; set; }
    }
}
