//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNegra
    {
        public int ID_ListaN { get; set; }
        public string Descripcion { get; set; }
        public string IdAspNetUsers { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Estatus { get; set; }
        public string Id_Empleado { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
