//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservacione()
        {
            this.Reservaciones_Usuarios = new HashSet<Reservaciones_Usuarios>();
        }
    
        public int ID_Reservacion { get; set; }
        public string ID_Empleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Cubiculo { get; set; }
        public System.DateTime FechaSolicitada { get; set; }
        public System.TimeSpan HSolicitada { get; set; }
        public System.TimeSpan HEntrada { get; set; }
        public System.TimeSpan HSalida { get; set; }
        public string Estatus { get; set; }
        public string IdAspNetUsers { get; set; }
    
        public virtual Cubiculo Cubiculo { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservaciones_Usuarios> Reservaciones_Usuarios { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
