//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad
    {
        public int ID_Seguridad { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string pregunta1 { get; set; }
        public string respuesta1 { get; set; }
        public string pregunta2 { get; set; }
        public string respuesta2 { get; set; }
        public bool status { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
