//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIREON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIREONEntitiess : DbContext
    {
        public SIREONEntitiess()
            : base("name=SIREONEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cubiculo> Cubiculos { get; set; }
        public virtual DbSet<ListaNegra> ListaNegras { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<R_Salas_Usuarios> R_Salas_Usuarios { get; set; }
        public virtual DbSet<R_Usuarios_Roles> R_Usuarios_Roles { get; set; }
        public virtual DbSet<Reservacione> Reservaciones { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Seguridad> Seguridads { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
